FROM node:20.15.0-alpine AS build
# FROM node:20.15.0-bullseye AS build

ARG build_env

WORKDIR /app

COPY package.json .

RUN yarn install --verbose

COPY . .

RUN apk add gettext

RUN yarn build:${build_env} --verbose

FROM nginx:1.26.2-alpine

RUN mkdir -p /usr/share/nginx/html/orcid-web-frontend

COPY --from=build /app/dist/ /usr/share/nginx/html/orcid-web-frontend/

EXPOSE 80

