on:
  workflow_call:
  workflow_dispatch:

name: test_yarn

jobs:
  test_yarn:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'v20.x'
          cache: 'yarn'
      - run: yarn
      - run: yarn test-headless
